version: '3'

volumes:
  mongo-rs0-keys:
  mongo-rs0-1:
  mongo-rs0-2:
  mongo-rs0-3:

networks:
  mongo-rs0-network:
    driver: bridge

services:
  mongo-rs0-keys:
    image: depop/openssl-bats
    volumes:
      - mongo-rs0-keys:/etc/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /etc/mongo-conf/mongodb-keyfile; chmod 600 /etc/mongo-conf/mongodb-keyfile; chown 999 /etc/mongo-conf/mongodb-keyfile"'

  mongo-rs0-1:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-rs0-1:/data/db
      - mongo-rs0-keys:/opt/keyfile
    depends_on:
      - "mongo-rs0-keys"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet rs0'
    networks:
      - mongo-rs0-network

  mongo-rs0-2:
    image: mongo:latest
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet rs0'
    volumes:
      - mongo-rs0-2:/data/db
      - mongo-rs0-keys:/opt/keyfile
    depends_on:
      - "mongo-rs0-keys"
    ports:
      - "27018:27017"
    networks:
      - mongo-rs0-network

  mongo-rs0-3:
    image: mongo:latest
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet rs0'
    volumes:
      - mongo-rs0-3:/data/db
      - mongo-rs0-keys:/opt/keyfile
    depends_on:
      - "mongo-rs0-keys"
    ports:
      - "27019:27017"
    networks:
      - mongo-rs0-network
      
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - "mongo-rs0-keys"
      - "mongo-rs0-1"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin //auth website (for auth when opening localhost:8081 or admin panel)
      ME_CONFIG_BASICAUTH_PASSWORD: admin //auth website (for auth when opening localhost:8081 or admin panel)
      ME_CONFIG_MONGODB_ADMINUSERNAME: root //auth based on MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: root //auth based on MONGO_INITDB_ROOT_PASSWORD
      ME_CONFIG_MONGODB_SERVER: 'mongo-rs0-1'
      ME_CONFIG_OPTIONS_EDITORTHEME: darcula
    ports:
      - "8081:8081"
    networks:
      - mongo-rs0-network

  setup-rs:
    image: "setup-rs"
    build: ./setup
    depends_on:
      - "mongo-rs0-1"
    networks:
      - mongo-rs0-network
